### PR TITLE
Added socket streaming of file content

### PR DESCRIPTION
**Pull request by metabiswadeep**
Allowed for socket streaming of file content (Part of cpdb-libs PR 30)

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Could you also add an updated `cpdb-text-frontend.c`? Thanks.

**Comment by metabiswadeep** [comment]
What should the file cpdb-text-frontend.c contain?

**Comment by tillkamppeter** [comment]
You have removed some functions from the API, so the appropriate parts needs to get removed from cpdb-text-frontend.c, so that it compiles.

**Comment by tillkamppeter** [comment]
Sorry, I am in the wrong repo. cpdb-text-frontend is in cpdb-libs ...

**Pull request merged**
